version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "56721:5672"  # RabbitMQ message broker
      - "25672:15672" # RabbitMQ management dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "63791:6379"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
