# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: docker compose -f "docker-compose.yml" up -d --build
      - name: Cache
        uses: actions/cache@v4.0.2
        id: cache-docker-layer
        with:
          key: ${{ hashFiles('docker-compose.yml') }}      
